# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailapp', '0004_blogpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='home_body',
        ),
    ]
