# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 14:56
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailapp', '0004_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtailapp.BlogCategory'),
        ),
    ]
