# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailapp', '0005_blogpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(default='(no author)', max_length=250),
        ),
    ]
