# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailapp', '0007_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailapp.Advert'),
        ),
    ]
