# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailapp', '0009_auto_20180531_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertBlogPageIndexRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailapp.AdvertSnippet')),
                ('blog_page_ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailapp.BlogIndexPage')),
            ],
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='its_ads',
            field=models.ManyToManyField(through='wagtailapp.AdvertBlogPageIndexRelationship', to='wagtailapp.AdvertSnippet'),
        ),
    ]
