# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-31 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailapp', '0011_blogadvertplacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='its_ads',
        ),
    ]
